spin_manifest_version = 2

[application]
name = "challenge2"
version = "0.1.0"
authors = ["Cute_Wisp <sweatpotato13@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "challenge2"

[component.challenge2]
source = "target/wasm32-wasi/release/challenge2.wasm"
allowed_outbound_hosts = []
[component.challenge2.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
