[package]
name = "challenge4"
authors = ["Cute_Wisp <sweatpotato13@gmail.com>"]
description = ""
version = "0.1.0"
rust-version = "1.78"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
serde_json = "1.0.134"
spin-sdk = "3.1.0"

[workspace]
